### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space....

### ISSUE THREAD

**Issue by sac111** [tushartushar/DesigniteJava#67]
I get the following error...

C:\>java -jar DesigniteJava.jar -i D:\Bukkit-master -o D:\results1
Parsing the source code ...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.lang.Throwable.getStackTraceElement(Native Method)
        at java.lang.Throwable.getOurStackTrace(Unknown Source)
        at java.lang.Throwable.printStackTrace(Unknown Source)
        at java.lang.Throwable.printStackTrace(Unknown Source)
        at org.eclipse.jdt.internal.compiler.util.Util.getExceptionSummary(Util.java:628)
        at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:589)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.handleInternalException(CompilationUnitResolver.java:357)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1222)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:689)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1183)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:809)
        at Designite.SourceModel.SM_Project.createAST(SM_Project.java:159)
        at Designite.SourceModel.SM_Project.createCompilationUnits(SM_Project.java:135)
        at Designite.SourceModel.SM_Project.parse(SM_Project.java:206)
        at Designite.Designite.main(Designite.java:28)

Kindly help me to remove the error...

**Comment by tushartushar** [comment]
This is not coming from the tool. It means your codebase size is way too big for the computer on which you are running it. There are some tricks that you may use to overcome this if you search the error message on Google. For example, take a look at this post: https://stackoverflow.com/questions/2381849/exception-in-thread-main-java-lang-outofmemoryerror-java-heap-space
